#!/bin/sh

#
# Make a certificate/private key pair using a locally generated
# root certificate.
#
# Explicitly set nsCertType to server using the "server"
# extension in the openssl.cnf file.

if test $# -ne 1; then
    echo "usage: build-key-server <name>";
    exit 1
fi

if test $KEY_DIR; then
    cd $KEY_DIR && \
   
    if [ ! -f "$1.key" ]; then
        echo "Generate key"
        openssl genrsa -rand /dev/urandom -out $1.key 2048
    else
        echo "Key exist, skip generating"    
    fi

    openssl req -days 3650 -new -key $1.key -out $1.csr -extensions server -subj "/C=${KEY_COUNTRY}/ST=${KEY_PROVINCE}/L=${KEY_CITY}/O=${KEY_ORG}/OU=${ORG_UNIT}/CN=$1" -config $KEY_CONFIG && \
    # not sure why but if use it openssl complain mismatch the KEY_PROVINCE even though it is the same
    #openssl ca -days 3650 -out $1.crt -in $1.csr -extensions server -subj "/C=${KEY_COUNTRY}/ST=${KEY_PROVINCE}/L=${KEY_CITY}/O=${KEY_ORG}/OU=${ORG_UNIT}/CN=$1" -config $KEY_CONFIG && \
    openssl ca -days 3650 -out $1.crt -in $1.csr -extensions server -config $KEY_CONFIG && \
    chmod 0600 $1.key

else
    echo you must define KEY_DIR
    exit 1
fi
