---
# handlers file for ansible-role-openvpn-server
- name: restart openvpn
  service: name=openvpn state=restarted enabled=yes

- name: reload systemd
  shell: "systemctl daemon-reload"

- name: reload ufw
  ufw: state=reloaded
